### PR TITLE
Add Steve Jobs: The Lost Interview

### PR DESCRIPTION
**Pull request by marciogomes**
Added the [Steve Jobs: The Lost Interview](https://www.youtube.com/watch?v=TRZAJY23xio) interview, which was hosted by the Robert X. Cringely. This interview is basically a conversation with Steve Jobs as he was running NeXT, the company he had founded after leaving Apple.

### CODE REVIEW

**Comment by watson** [comment]
@marciogomes Thanks for the contribution :smiley: Could I get you to break up each submission it it's own pull request?

**Comment by marciogomes** [comment]
Can you do it for me? I'm very beginner with Git/Github. I tried to split this pull request into other, but seems that merge it.
(Sorry with my english)

**Comment by marciogomes** [comment]
Revert the branch to the commi that I added just the interview.

**Comment by watson** [comment]
@marciogomes #7 beat you to it with The Lost Interview. I'm closing this one, but I hope you'll submit "The Humble Programmer" as another PR. It's a really interesting story that I didn't know about :smiley:

**Comment by marciogomes** [comment]
Thanks!

**Pull request closed without merging**
