### PR TITLE
Added Revolution OS

### PR DESCRIPTION
**Pull request by vivekanand1101**

### CODE REVIEW

**Comment by watson** [comment]
@vivekanand1101 Nice - didn't know that one :) The linked video have english subtitles burned in. I found another version which didn't: https://www.youtube.com/watch?v=jw8K460vx1c

Can you link to that one instead?

**Comment by watson** [comment]
Can I also get you to add a space between the link and the year?

**Comment by vivekanand1101** [comment]
Doing it wait :)

**Comment by vivekanand1101** [comment]
@watson  done!

**Comment by watson** [comment]
@vivekanand1101 thanks :)

**Pull request merged**
