### PR TITLE
Added two documentaries

### PR DESCRIPTION
**Pull request by joshuatvernon**
Silicon Cowboys - A documentary about the PC company Compaq.
The Story of Google - A documentary about the story of Google.

### CODE REVIEW

**Comment by watson** [comment]
Awesome, thanks @jamesdwilson - I don't know why I didn't have Silicon Cowboys on the list 👍 I like it!

The one you call "The Story of Google" is actually episode 2, "Search" of the mini series "[Download: The True Story of the Internet](https://en.wikipedia.org/wiki/Download_The_True_Story_of_the_Internet)" - I can recommend the other episodes as well 🙂

I'm just going to merge this one now and update it in master as that's probably quicker.

**Comment by jamesdwilson** [comment]
very cool, thanks!

**Comment by watson** [comment]
Ha, GitHub autocomplete - Typed @j and selected the wrong suggestion, sorry ;) Should have been @joshuatvernon

**Comment by watson** [comment]
But I fund all the episodes of in the series and added them as well - so there's that: https://github.com/watson/awesome-computer-history/commit/e5cc229eb541d2abda314895c90617ed178a156d

**Comment by watson** [comment]
Haha! I did it again - I should just show my self out, sorry everybody

**Comment by joshuatvernon** [comment]
@watson No worries. I'll check out the other episodes and as I find more content I'll assist. Thanks!

**Pull request merged**
